<?php

namespace AppBundle\Repository;

/**
 * ProtocolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProtocolRepository extends \Doctrine\ORM\EntityRepository
{
}
