#!
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

adviser_protocol_index:
    path:     "%urls.adviser_protocol_index%"
    defaults: { _controller: "AppBundle:Adviser:protocols" }
    methods:  GET

