#!
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

adviser_protocol_index:
    path:     "%urls.adviser_protocol_index%"
    defaults: { _controller: "AppBundle:Adviser:protocols" }
    methods:  GET

adviser_protocol_generate:
    path:     "%urls.adviser_protocol_generate%"
    defaults: { _controller: "AppBundle:Adviser:generateProtocol" }
    methods:  [GET, POST]

adviser_protocol_config:
    path:     "%urls.adviser_protocol_config%"
    defaults: { _controller: "AppBundle:Adviser:configProtocol" }
    methods:  [GET, POST]

adviser_buy_pack:
    path:     "%urls.adviser_buy_pack%"
    defaults: { _controller: "AppBundle:Adviser:buyPack" }
    methods:  [GET, POST]

advisers_list:
    path:     "%urls.advisers_list%"
    defaults: { _controller: "AppBundle:User:advisersList" }
    methods:  GET

