#!
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

protocol_index:
    path:     "%urls.protocol_index%"
    defaults: { _controller: "AppBundle:Protocol:index" }
    methods:  GET

protocol_buy:
    path:     "%urls.protocol_buy%"
    defaults: { _controller: "AppBundle:Protocol:buy" }
    methods:  [GET, POST]

protocol_pay:
    path:     "%urls.protocol_pay%"
    defaults: { _controller: "AppBundle:Protocol:pay" }
    methods:  [GET, POST]

protocol_pay_transfer:
    path:     "%urls.protocol_pay_transfer%"
    defaults: { _controller: "AppBundle:Protocol:payTransfer" }
    methods:  GET

protocol_paid:
    path:     "%urls.protocol_paid%"
    defaults: { _controller: "AppBundle:Protocol:paymentComplete" }
    methods:  GET

protocol_download:
    path:     "%urls.protocol_download%"
    defaults: { _controller: "AppBundle:Protocol:download" }
    methods:  GET

protocol_download_instructions:
    path:     "%urls.protocol_download_instructions%"
    defaults: { _controller: "AppBundle:Protocol:downloadInstructions" }
    methods:  GET

protocol_download_recibi:
    path:     "%urls.protocol_download_recibi%"
    defaults: { _controller: "AppBundle:Protocol:downloadRecibi" }
    methods:  GET

protocol_admin_index:
    path:     "%urls.protocol_admin_index%"
    defaults: { _controller: "AppBundle:Protocol:indexAdmin" }
    methods:  GET

protocol_create:
    path:     "%urls.protocol_create%"
    defaults: { _controller: "AppBundle:Protocol:create" }
    methods:  [GET, POST]

protocol_config:
    path:     "%urls.protocol_config%"
    defaults: { _controller: "AppBundle:Protocol:config" }
    methods:  [GET, POST]

protocol_admin_download:
    path:     "%urls.protocol_admin_download%"
    defaults: { _controller: "AppBundle:Protocol:downloadAdmin" }
    methods:  GET

protocol_admin_download_instructions:
    path:     "%urls.protocol_admin_download_instructions%"
    defaults: { _controller: "AppBundle:Protocol:downloadInstructionsAdmin" }
    methods:  GET

protocol_admin_download_recibi:
    path:     "%urls.protocol_admin_download_recibi%"
    defaults: { _controller: "AppBundle:Protocol:downloadRecibiAdmin" }
    methods:  GET

protocol_admin_html:
    path:     "%urls.protocol_admin_html%"
    defaults: { _controller: "AppBundle:Protocol:htmlAdmin" }
    methods:  GET

protocol_admin_delete:
    path:     "%urls.protocol_admin_delete%"
    defaults: { _controller: "AppBundle:Protocol:deleteAdmin" }
    methods:  GET

protocol_public_redes:
    path:     "%urls.protocol_public_redes%"
    defaults: { _controller: "AppBundle:Protocol:publicRedes" }
    methods:  GET

protocol_public_equipos:
    path:     "%urls.protocol_public_equipos%"
    defaults: { _controller: "AppBundle:Protocol:publicEquipos" }
    methods:  GET

protocol_public_mensajeria:
    path:     "%urls.protocol_public_mensajeria%"
    defaults: { _controller: "AppBundle:Protocol:publicMensajeria" }
    methods:  GET

adviser_protocol_index:
    path:     "%urls.protocol_index%"
    defaults: { _controller: "AppBundle:Protocol:index" }
    methods:  GET

