#!/bin/bash
#
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

get_config() {
    key=$1

    grep $key ${script_dir}/parameters.yml | awk 'BEGIN {FS=":"} {print $2}' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'
}

err=${script_dir}/error.log
out=${script_dir}/out.log

target=${1:-pre}
server=$(get_config "server")

run_scp() {
    local_file=$1
    remote_file=$2

    echo "    scp ${local_file} ${remote_file}"

    scp ${local_file} ${remote_file} > $out  2> $err || {
        echo '        << failed >>'
        exit 1
    }
}

run_ssh() {
    command=$1
    remote_file=$2

    echo "    ssh ${server} "'"'$command'"'

    ssh ${server} "$command" > $out 2> $err || {
        echo '        << failed >>'
        exit 1
    }
}

deploy() {
    target=$1
    remote_folder=$2
    server=$(get_config "server")

    rm -f $err
    rm -f $out

    echo "Deploying $target... "

    run_scp "${script_dir}/.htaccess"_"${target} ${server}:${remote_folder}/.htaccess"

    run_ssh "cd ${remote_folder} && git checkout -- . && git fetch && git pull --rebase"

    run_ssh "cd ${remote_folder} && php tools/composer.phar update && php tools/composer.phar install"

    run_scp "${script_dir}/parameters_${target}.yml" "${server}:${remote_folder}/app/config/parameters.yml"

    run_scp "${script_dir}/wp-config_${target}.php" "${server}:${remote_folder}/web/blog/wp-config"

    run_ssh "cd ${remote_folder} && php bin/console doctrine:migrations:migrate"

    run_ssh "cd ${remote_folder} && php bin/console cache:clear --env=prod"
}

case "$target" in
    pre)
        deploy $target "www/pre"
        ;;
    pro)
        deploy $target "www"
        ;;
esac
