#!/bin/bash
#
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

compile_tex() {
    filename=$1

    cd $dir/src && pdflatex $filename.tex
    cd $dir/src && pdflatex $filename.tex

    rm $dir/src/*.aux
    rm $dir/src/*.log
    rm $dir/src/*.toc
    rm $dir/src/*.out

    mv $dir/src/$filename.pdf $dir/pdf/$filename.pdf

    open $dir/pdf/$filename.pdf
}

compile_tex "manual_cliente"
compile_tex "manual_admin"
