#!
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /

app_profile:
    resource: "@AppBundle/Resources/config/routing/profile.yml"
    prefix:   /

app_invoice:
    resource: "@AppBundle/Resources/config/routing/invoice.yml"
    prefix:   /

app_protocol:
    resource: "@AppBundle/Resources/config/routing/protocol.yml"
    prefix:   /

app_order:
    resource: "@AppBundle/Resources/config/routing/order.yml"
    prefix:   /

app_adviser:
    resource: "@AppBundle/Resources/config/routing/adviser.yml"
    prefix:   /

