#!
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

AppBundle\Entity\Pack:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PackRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        user:
            type: integer
        invoice:
            type: integer
            nullable: true
        enabled:
            type: boolean
            column: enabled
            nullable: false
        amount:
            type: integer
            nullable: false
        orderHash:
            type: string
            length: '8'
            nullable: true
            column: order_hash
        orderDate:
            type: date
            column: order_date
        price:
            type: integer
    lifecycleCallbacks: {  }
